/*!
\mainpage Overview
\section sec_intro About this manual
	This manual is automatically generated by Doxygen.
\section Author
	Kyuyeon Hwang (Signal Processing Systems Laboratory, Seoul National University, Seoul, Korea)
\section sec_license License
	Apache license version 2.0
*/
